version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - "2184:2184"
  kafka:
    image: wurstmeister/kafka
    ports:
    - "9093:9093"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test_topic:1:3"